services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fruit
      POSTGRES_USER: fruit
      POSTGRES_PASSWORD: fruit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
